version: '3.1'

services:
  postgres-database:
    container_name: proffy-postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proffy
      PGDATA: /data/postgres
    volumes:
      - .postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin@email.com"
    ports:
      - "16543:80"
    depends_on:
      - postgres-database
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge